<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Kvit.Application\Kvit.Application.csproj" />
    <ProjectReference Include="..\Kvit.Domain\Kvit.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

</Project>
