<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>bcfd86db-4cb9-4420-a51b-07280be4c0d1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kvit.Application\Kvit.Application.csproj" />
    <ProjectReference Include="..\Kvit.Contracts\Kvit.Contracts.csproj" />
    <ProjectReference Include="..\Kvit.Domain\Kvit.Domain.csproj" />
    <ProjectReference Include="..\Kvit.Infrastructure\Kvit.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

</Project>
